apiVersion: boom.caos.ch/v1beta1
kind: Toolset
metadata:
  name: caos
  namespace: caos-system
spec:
  preApply:
    deploy: false
    folder: preapply
  postApply:
    deploy: false
    folder: postapply
  prometheus-operator:
    deploy: true
  logging-operator:
    deploy: true
  prometheus-node-exporter:
    deploy: true
  grafana:
    deploy: true
  ambassador:
    deploy: true
    service:
      type: LoadBalancer
  kube-state-metrics:
    deploy: true
  argocd:
    deploy: false
    customImage:
      enabled: false
      imagePullSecret: github-image
      gopassGPGKey: "gpg"
      gopassSSHKey: "ssh"
      gopassStores:
      - directory: "directory"
        storeName: "store"
  prometheus:
    deploy: true
    storage:
      size: 5Gi
      storageClass: standard
  loki:
    deploy: true
    # storage:
    #   size: 5Gi
    #   storageClass: standard